[tox]
envlist = format, lint, test
skip_missing_interpreters = true

[testenv:format]
deps = black
commands = 
    black --check .

[testenv:lint]
deps = ruff
commands =
    ruff check .

[testenv:test]
deps =
    coverage
commands =
    coverage run -m unittest discover -s tests
    coverage report -m